### ISSUE TITLE
Sending Stats

### ISSUE THREAD

**Issue by RainbowTea** [lucyydotp/pronouns3#18]
Can this be turned off?

[04:31:44 WARN]: [ProNouns] sending stats
[04:31:45 WARN]: [ProNouns] 204

It just sends over and over every 15 minutes. Not a  fan of it lol.

**Comment by lucyydotp** [comment]
This is a debug message I accidentally left in, I will be removing it in the next build.
Please do read the docs (https://lucyydotp.github.io/pronouns3), _especially_ if you're using pre-production builds.
