### ISSUE TITLE
TAB placeholders

### ISSUE THREAD

**Issue by RainbowTea** [lucyydotp/pronouns3#19]
So, How do I allow it to show more than one pronoun as a placeholder?

I've tried all the ones in this list for paper and it doesn't seem to show  more than he or he/him.  For example people use he/they. I want that to show. But it ONLY shows the first pronoun as the main one in the placeholder.

Image: https://prnt.sc/IWPlDVDLNUh6

https://lucyydotp.github.io/pronouns3/placeholders.html

I am using: 

pronouns-paper-3.0.0-alpha.4
Paper version git-Paper-439 (MC: 1.19.3)
TAB v3.2.4 (though making this post i realize there's an update for it i will have to update to later)

**Comment by lucyydotp** [comment]
The placeholder `%pronouns_pronouns%` should be showing all sets already - this may be a bug

**Comment by ivybowman** [comment]
![image](https://user-images.githubusercontent.com/18595973/222989355-b9dd00b6-1d4b-4e21-8432-3e4c9ea59b48.png)
Same issue with that placeholder, the exact command I used was `/pn set she/they`

**Comment by lucyydotp** [comment]
Noted, this is most likely a bug then

**Comment by RainbowTea** [comment]
Thank you so much for getting back to me quickly :) Let me know if there's any other information I can provide. I  love the plugin.

**Comment by lucyydotp** [comment]
Fixed in 89f86a9795207e00321b88e72c47b3560d372055, will be included in the next update.
