### ISSUE TITLE
MariaDB Crash on start Issue

### ISSUE THREAD

**Issue by ivybowman** [lucyydotp/pronouns3#20]
Fatal error when using database store with Server version: 10.6.11-MariaDB-log MariaDB Server. 
Stack traces from sentry attached below ZIP because GitHub doesn't like JSON files. This worked before I switched to the MySQL store.

[Stacktraces.zip](https://github.com/lucyydotp/pronouns3/files/10893166/Stacktraces.zip)

**Comment by ivybowman** [comment]
Perhaps this is caused by MySQL syntax not translating properly even though it SHOULD be a drop-in replacement.

**Comment by lucyydotp** [comment]
This is caused by my use of the UUID SQL data type which only exists in very new versions of mariadb

**Comment by ivybowman** [comment]
Thanks! I should probably update MariaDB lol.

**Comment by lucyydotp** [comment]
Resolved in 3.0.0-alpha.5
