### ISSUE TITLE
Player argument ignored when attempting to set another player's pronouns

### ISSUE THREAD

**Issue by TheCatMan2000** [lucyydotp/pronouns3#23]
![image](https://user-images.githubusercontent.com/27119164/234172665-4f20102c-a37c-469b-9cf2-f01251809dc1.png)
Just changes the pronouns of the player who ran the command.

Unsure if this has to do with that specific player not having joined the server yet.

On 3.0.0-alpha 6

**Comment by lucyydotp** [comment]
Please see #27.
