### ISSUE TITLE
SSL Validation fails when trying to upload statistic

### ISSUE THREAD

**Issue by Space-G** [lucyydotp/pronouns3#25]
Approximately every 30 minutes my Paper 1.20.4 (build 450) Server logs the following warning:

`[ProNouns] Failed to upload statistics. Please report this!javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed`

Please let me know if any more information is needed.

**Comment by CassieRoseZA** [comment]
Same here

**Comment by CassieRoseZA** [comment]
[19:28:17 WARN]: [ProNouns] Failed to upload statistics. Please report this!javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

**Comment by CassieRoseZA** [comment]
i think i found a workaround
in pronouns.cfg
set `# ---
# Stats
# ---

# Whether to send anonymous statistics information about the plugin.
# Defaults to true. See the documentation for more information.
stats = false`
to false

**Comment by lucyydotp** [comment]
Please see #27.
